version: '3.8'
services:
  dashboard-intanet:
    image: ghcr.io/badru9/dashboard-intanet:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    # Uncomment and adjust the port mapping if you need to expose the application directly.
    # The format is HOST_PORT:CONTAINER_PORT
    # ports:
    #   - "8000:80"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # The following are needed for the application to run correctly inside the container
      - APP_LOG_LEVEL=debug
      - LOG_CHANNEL=stack
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
